"""
Evaluate a frontier model on the 4-class SWMH task via OpenRouter.

This script was missing from the repository: four of the ten result files
(GPT and Claude, full and stripped) could not be regenerated by anyone
cloning it. This closes that gap.

Why OpenRouter rather than each vendor's own SDK:
  - One API key and one request format for every model, so adding a third
    or fourth frontier model to address the "only two models, and they
    disagreed" limitation costs one command-line flag instead of a new
    integration.
  - Usually cheaper per token than going direct, and it exposes per-request
    cost so the spend is auditable rather than a surprise at month end.
  - Model identifiers are explicit and versioned (e.g.
    "openai/gpt-4o-2024-11-20"), which matters because this paper's
    operational definition of "frontier" is tied to specific named
    versions rather than to parameter counts.

Design decisions that matter for the paper's claims:

  - RESUMABLE. Results are appended to a JSONL cache after every call. Re-
    running skips posts already done. An interrupted 9,167-post run costs
    nothing to restart, and a rate-limit error does not throw away an hour
    of spend.

  - REFUSAL AND UNPARSEABLE ARE SEPARATE METRICS. A model that declines to
    answer is doing something different from a model that answers in a
    format the parser cannot read. Conflating them, or scoring both as
    misclassification, hides the distinction. The Claude Haiku result in
    this study turned on exactly that difference: 67.9% unparseable against
    under 0.1% refusal.

  - TEMPERATURE 0, FIXED PROMPT. The prompt template is identical to the
    one used for the fine-tuned condition and is intentionally minimal. Any
    per-model prompt tuning would give some models an advantage the others
    did not get, which would defeat the controlled comparison. Prompt
    sensitivity is a separate experiment, not a fix to this one.

Usage:
    export OPENROUTER_API_KEY=sk-or-...
    python src/run_frontier.py --model openai/gpt-4o --variant full
    python src/run_frontier.py --model anthropic/claude-3.5-haiku --variant stripped

    # cheap sanity check before committing to a full run
    python src/run_frontier.py --model openai/gpt-4o --variant full --limit 50
"""

import argparse
import json
import os
import re
import sys
import time

import pandas as pd
import requests
from tqdm import tqdm

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from labels import LABELS, strip_keywords  # noqa: E402

API_URL = "https://openrouter.ai/api/v1/chat/completions"

# Identical to the fine-tuned condition's prompt. Do not tune per model.
PROMPT = (
    "Classify the following Reddit post into exactly one category: "
    "depression, SuicideWatch, Anxiety, or bipolar.\n\n"
    "Post: {text}\n\nCategory:"
)

# Phrases indicating the model declined rather than failed to format.
# Checked before label matching, since a refusal can incidentally contain a
# label word ("I can't diagnose depression from a post").
REFUSAL_MARKERS = [
    "i can't", "i cannot", "i'm not able", "i am not able",
    "i'm unable", "i am unable", "as an ai", "i won't", "i will not",
    "not appropriate", "cannot provide", "can't provide",
    "seek professional", "consult a", "i'm sorry, but",
]


def classify_response(text):
    """Return (label, status). status in {ok, refusal, unparseable}."""
    if text is None:
        return None, "unparseable"
    low = text.strip().lower()
    if not low:
        return None, "unparseable"

    # Refusal check first: a decline may mention a label word in passing.
    if any(m in low for m in REFUSAL_MARKERS):
        return None, "refusal"

    # Prefer a whole-word match anchored near the start of the response.
    for lab in LABELS:
        if re.search(r"\b" + re.escape(lab.lower()) + r"\b", low):
            return lab, "ok"
    return None, "unparseable"


def call_model(model, text, api_key, max_retries=5):
    """One request. Returns (content, cost_usd). Retries on 429 and 5xx."""
    payload = {
        "model": model,
        "messages": [{"role": "user", "content": PROMPT.format(text=text)}],
        "temperature": 0,
        "max_tokens": 12,
    }
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    delay = 2.0
    for attempt in range(max_retries):
        try:
            r = requests.post(API_URL, json=payload, headers=headers, timeout=60)
            if r.status_code == 429 or r.status_code >= 500:
                time.sleep(delay)
                delay = min(delay * 2, 60)
                continue
            r.raise_for_status()
            data = r.json()
            content = data["choices"][0]["message"]["content"]
            cost = float(data.get("usage", {}).get("total_cost", 0.0) or 0.0)
            return content, cost
        except requests.RequestException:
            if attempt == max_retries - 1:
                return None, 0.0
            time.sleep(delay)
            delay = min(delay * 2, 60)
    return None, 0.0


def load_cache(path):
    done = {}
    if os.path.exists(path):
        with open(path) as f:
            for line in f:
                try:
                    rec = json.loads(line)
                    done[rec["idx"]] = rec
                except json.JSONDecodeError:
                    continue  # tolerate a truncated final line
    return done


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True,
                    help="OpenRouter model id, e.g. openai/gpt-4o")
    ap.add_argument("--variant", choices=["full", "stripped"], required=True)
    ap.add_argument("--redaction-mode", default="delete",
                    choices=["delete", "neutral", "mask"],
                    help="how stripped text is redacted; see labels.py")
    ap.add_argument("--data-dir", default="data/processed/4class")
    ap.add_argument("--out-dir", default="results")
    ap.add_argument("--limit", type=int, default=None,
                    help="evaluate only the first N posts (cost sanity check)")
    ap.add_argument("--sleep", type=float, default=0.0,
                    help="seconds between calls if rate limited")
    args = ap.parse_args()

    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        raise SystemExit("Set OPENROUTER_API_KEY in your environment.")

    test = pd.read_csv(os.path.join(args.data_dir, "test.csv"))
    if args.variant == "stripped":
        test["text"] = test["text"].astype(str).apply(
            lambda t: strip_keywords(t, mode=args.redaction_mode)
        )
    if args.limit:
        test = test.head(args.limit)

    slug = args.model.replace("/", "-").replace(".", "_")
    os.makedirs(args.out_dir, exist_ok=True)
    cache_path = os.path.join(args.out_dir, f"cache_{slug}_{args.variant}.jsonl")
    cache = load_cache(cache_path)
    print(f"{args.model} | {args.variant} | {len(test)} posts "
          f"| {len(cache)} already cached")

    total_cost = sum(r.get("cost", 0.0) for r in cache.values())

    with open(cache_path, "a") as cf:
        for idx, row in tqdm(test.iterrows(), total=len(test), desc="Querying"):
            if idx in cache:
                continue
            content, cost = call_model(args.model, str(row["text"]), api_key)
            label, status = classify_response(content)
            rec = {
                "idx": int(idx),
                "true": row["label"],
                "raw": content,
                "pred": label,
                "status": status,
                "cost": cost,
            }
            cf.write(json.dumps(rec) + "\n")
            cf.flush()  # survive a crash mid-run
            cache[idx] = rec
            total_cost += cost
            if args.sleep:
                time.sleep(args.sleep)

    # Score. Refusals and unparseables are counted separately AND scored as
    # errors, matching how the fine-tuned conditions are scored, so the
    # comparison stays like-for-like.
    from sklearn.metrics import classification_report, f1_score

    recs = [cache[i] for i in sorted(cache) if i in test.index]
    true = [r["true"] for r in recs]
    pred = [r["pred"] if r["pred"] else "UNKNOWN" for r in recs]

    n = len(recs)
    n_refusal = sum(r["status"] == "refusal" for r in recs)
    n_unparse = sum(r["status"] == "unparseable" for r in recs)

    report = classification_report(true, pred, labels=LABELS,
                                   output_dict=True, zero_division=0)
    macro_f1 = f1_score(true, pred, labels=LABELS, average="macro",
                        zero_division=0)

    print(classification_report(true, pred, labels=LABELS, zero_division=0))
    print(f"macro-F1:      {macro_f1:.4f}")
    print(f"refusal:       {n_refusal / n * 100:.2f}%")
    print(f"unparseable:   {n_unparse / n * 100:.2f}%")
    print(f"total cost:    ${total_cost:.4f}")

    out = {
        "model": args.model,
        "provider": "openrouter",
        "variant": args.variant,
        "redaction_mode": args.redaction_mode if args.variant == "stripped" else None,
        "macro_f1": macro_f1,
        "anxiety_f1": report.get("Anxiety", {}).get("f1-score"),
        "refusal_rate": n_refusal / n,
        "unparseable_rate": n_unparse / n,
        "full_report": report,
        "n_test": n,
        "total_cost_usd": round(total_cost, 4),
    }
    out_path = os.path.join(args.out_dir, f"results_{slug}_{args.variant}.json")
    with open(out_path, "w") as f:
        json.dump(out, f, indent=2)
    print(f"\nSaved to {out_path}")


if __name__ == "__main__":
    main()